# Generated by Django 2.0 on 2018-10-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodingAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isCurrent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isCurrent', models.BooleanField(default=False)),
            ],
        ),
    ]
