# Generated by Django 2.0 on 2018-10-20 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileHandler', '0002_lodingaudio_welcomeaudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLodingAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isCurrent', models.BooleanField(default=False)),
                ('device_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceLodingAudio', to='fileHandler.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceWelcomeAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isCurrent', models.BooleanField(default=False)),
                ('device_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceWelcomeAudio', to='fileHandler.Device')),
            ],
        ),
        migrations.DeleteModel(
            name='LodingAudio',
        ),
        migrations.DeleteModel(
            name='WelcomeAudio',
        ),
    ]
