# Generated by Django 2.0 on 2018-10-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileHandler', '0003_auto_20181020_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_Id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('player_name', models.FileField(upload_to='')),
            ],
        ),
    ]
